global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes its own metrics

  - job_name: 'dydxprotocol-node0'
    static_configs:
      - targets: ['dydxprotocol-node0:26660'] # Metrics endpoint

  - job_name: 'dydxprotocol-node1'
    static_configs:
      - targets: ['dydxprotocol-node1:26660'] # Metrics endpoint

  - job_name: 'dydxprotocol-node2'
    static_configs:
      - targets: ['dydxprotocol-node2:26660'] # Metrics endpoint

  - job_name: 'dydxprotocol-node3'
    static_configs:
      - targets: ['dydxprotocol-node3:26660'] # Metrics endpoint

